server:
  addrs:
    - http: 0.0.0.0:40772
  mounts:
      /miraview:
        path: /var/www/miraview
        index: index.html
epg:
  cache-dir: /var/lib/mirakc/epg

recording:
  basedir: /var/lib/mirakc/recording
  
channels:

tuners:

